### ISSUE TITLE
Game Pass information

### ISSUE THREAD

**Issue by geeseven** [MarsRaptor/brasspoll#4]
Hey @MarsRaptor,

What do you think about adding some indication if a game is on Game Pass?  

From what I can tell, Microsoft does not have an API to get a list of games on Game Pass.  IGDB does not have Game Pass as a platform.  I could not find any API that provides games on Game Pass.  I am able to get a list via screen scarping PCGamingWiki:

```python
#!/usr/bin/env python
import re
import requests

url="https://www.pcgamingwiki.com/wiki/List_of_Xbox_Game_Pass_games"
regex=r'class="table-xbox-body-game"><a.*>(.*)<\/a>'

r = requests.get(url)

games = re.findall(regex, r.text)

print(*games, sep="\n")
``` 

```console
$ ./gamepass.py 
A Plague Tale: Innocence
ARK: Survival Evolved
Age of Empires II: Definitive Edition
Age of Empires III: Definitive Edition
Age of Empires: Definitive Edition
Age of Wonders: Planetfall
Alan Wake
Alien: Isolation
Alvastia Chronicles
Among Us
...

```

I did attempt to try to get information from Game Pass list of games [page], but that page is super complicated.  Loading that site, it does 181 other requests.  I am not sure if there was be any sensible way to extract Game Pass games that page.

[page]: https://www.xbox.com/en-US/xbox-game-pass/games

**Comment by MarsRaptor** [comment]
**I'm gathering that you imagine a flag to be set on the details for game results that indicates if it is on game pass, if that's the case here's the rub :** 
- Brasspoll is not a game poll creator. At it's core it is a strawpoll.me creation tool with extended features, each plugin is independent from each other. So the underlying issue is that I would have to add a version of the proposed "gamepass flag" feature on each plugin concerned, and that feature could vary in implementation on a per plugin basis. That requires work and that's not my credo xD .
- As a soft rule, I try to keep the number of different sites for data aggregation per plugin down to a minimum, by that I mean I don't want to search IGDB for details about a Steam result.
- Related to the previous statement, the workaround involves a 3rd party data scraper. This means I would need to scrape data from X that scrapes data from Y to add to details to a plugin intended for Z. In short, if I want Microsoft's data I'll  fetch it from Microsoft or an affiliate.
- The workaround gives us a list of links to work with, this leaves us with bad solutions for result linking:
  - A fuzzy string comparison on titles, this will be riddled with false positives and negatives so it's unreliable.
  - Diving into each link and scraping to find a reliable unique identifier, this relies on the pages being kept up to snuff and being up to date which implies I either : 
    - Manually request a purge of the games periodically to keep the list up to date.
    - Automate the purge, which would be a pain in the rear. 
    - Store a replicated version (still requires updating) of the data in local storage. This means I would share this between plugins, I'm not a fan.

**For those reasons I will not go ahead with that idea, BUT that doesn't mean I can't do 1 of 2 things from the top of my head :** 
1. Create a [pcgamingwiki "List_of_Xbox_Game_Pass_games"](https://www.pcgamingwiki.com/wiki/List_of_Xbox_Game_Pass_games) plugin, I would need handle the purge updating but this keeps with the philosophy of 1 plugin for 1 site. The details could be the associated pcgamingwiki page. It would require an extra click from the user on one of the "Availability" links to view more information about the game but it's doable.
2. Create a Microsoft game plugin, as you mentioned the [Xbox site](https://www.xbox.com/en-US/xbox-game-pass/games) isn't really exploitable since it tries hard to keep it's workings hidden and uses auth keys every which where. But I may have found a way to hack the planet using the Microsoft Store. There is more than 1 way to skin a cat as they say, or more than 1 way to scrape a site xD <br><img src="https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/Villainc.svg/220px-Villainc.svg.png" width="100">

**Comment by geeseven** [comment]
Hey @MarsRaptor,

Thanks for the very detailed answer. All of what you said is very reasonable.  

FYI, I have updated my method for getting Game Pass games to use the MediaWiki API.

```python
#!/usr/bin/env python
from requests import get


def get_pcgamingwiki(condition):
    games = []
    url = (
        "https://www.pcgamingwiki.com/w/api.php?action=askargs&format=json&conditions="
        + condition
    )
    r = get(url)
    while True:
        for item in list(r.json()["query"]["results"].keys()):
            games.append(item)
        try:
            r.json()["query-continue-offset"]
        except KeyError:
            break
        else:
            offset = str(r.json()["query-continue-offset"])
            r = get(url + "&parameters=offset=" + offset)
    return games


game_pass_list = get_pcgamingwiki("Microsoft Store Game Pass::true")
print(*game_pass_list, sep="\n")
```

```console
$ ./pcgamingwiki-api.py 
A Plague Tale: Innocence
ARK: Survival Evolved
Age of Empires II: Definitive Edition
Age of Empires III: Definitive Edition
Age of Empires: Definitive Edition
Age of Wonders: Planetfall
Alan Wake
Alien: Isolation
Alvastia Chronicles
Among Us
...
```

Granted this still just getting game names, as you mentioned is problematic.  I am still working on getting something like steam app id from a game name.  Even with a steam app id, there is still room for false negatives.  Steam only has 'Control Ultimate Edition' while Game Pass has 'Control'.

PCGamingWiki also has information about games on EA Play Pro (EA Play Pro::true) and Ubisoft+ (Ubisoft Plus::true) subscription services.

**Comment by geeseven** [comment]
> find a reliable unique identifier

[PCGamingWiki][0] has these IDs:
GOG
IsThereAnyDeal
Humble Store
Epic Games Store
[Steam][1] (not sure why it isn't showing up when searching)


[IGDB][2] has these IDs:
Steam
GOG
YouTube
Microsoft
Apple
Twitch
Android

[0]: https://www.pcgamingwiki.com/w/index.php?search=Property%3A*ID*&title=Special%3ASearch&profile=default&fulltext=1
[1]: https://www.pcgamingwiki.com/wiki/Property:Steam_AppID
[2]: https://api-docs.igdb.com/#external-game

**Comment by geeseven** [comment]
>  I am still working on getting something like steam app id from a game name.

Found the API call.

```python
#!/usr/bin/env python
from requests import get


def get_pcgamingwiki(condition):
    games = []
    url = (
        "https://www.pcgamingwiki.com/w/api.php?action=askargs&printouts=Steam_AppID&format=json&conditions="
        + condition
    )
    r = get(url)
    while True:
        for item in list(r.json()["query"]["results"].keys()):
            games.append((item, r.json()["query"]["results"][item]['printouts']['Steam_AppID']))
        try:
            r.json()["query-continue-offset"]
        except KeyError:
            break
        else:
            offset = str(r.json()["query-continue-offset"])
            r = get(url + "&parameters=offset=" + offset)
    return games


game_pass_list = get_pcgamingwiki("Microsoft Store Game Pass::true")
print(*game_pass_list, sep="\n")
```

```console
$ ./pcgamingwiki-api.py |head --lines=10
('A Plague Tale: Innocence', [752590, 967380])
('ARK: Survival Evolved', [346110])
('Age of Empires II: Definitive Edition', [813780])
('Age of Empires III: Definitive Edition', [933110])
('Age of Empires: Definitive Edition', [1017900])
('Age of Wonders: Planetfall', [718850, 1078840, 1124910, 1137800, 1137801])
('Alan Wake', [108710, 108726, 268560])
('Alien: Isolation', [214490])
('Alvastia Chronicles', [948660])
('Among Us', [945360])
```

Note, I am investigating this for another project and figured it _might_ be useful here.

**Comment by geeseven** [comment]
> Even with a steam app id, there is still room for false negatives. Steam only has 'Control Ultimate Edition' while Game Pass has 'Control'.

Looking over the PCGamingWiki data for 'Control', they have the steam app id for 'Control Ultimate Edition'.  I am thinking that false negatives for different editions of the same game is not going to be as big as a deal.

PCGamingWiki users have not flagged Control as being on Game Pass yet.  Looking over the [games recently added to Game Pass][0], Control is one of two games PCGamingWiki does not show is part of Game Pass.  I think that is to be excepted from a user generated data set.


[0]: https://www.ign.com/articles/control-may-be-coming-to-xbox-game-pass-in-december-2020

**Comment by MarsRaptor** [comment]
After another quick look my intuition tells me that the pcgamingwiki list of game pass games scrapes [Microsoft's collection of pc games a-z](https://www.microsoft.com/en-us/store/collections/pcgavtaz) when it does it's "purge" call .  This means that the information is legit if it is updated after a new game roster hits game pass. 
On your issue of Control, the Microsoft store marks it as a _console only offer_ so I think the list is probably the best for your use case right now.
![ControlXboxGamePass](https://user-images.githubusercontent.com/14842426/102516707-75747700-408f-11eb-90d0-d60c3d434524.JPG) 
One hurdle that I've seen when retrieving the wiki data is that it uses pages of 50 for the results by default, I think it mentions somewhere in the docs that it's 50 results max per call for users and 500 max for registered bots. You might have seen this, but it's a heads up that you would need to chain calls just in case.

**Comment by geeseven** [comment]
That a-z game page shows 239 items, while I am getting 250 items from PCGamingWiki API.  There are also these three weird results.

```console
$ ./pcgamingwiki-api.py
...
('We Happy Few', [320240, 908420])
('User:Weion/Sandbox/Games/HaloMCC', [])
('User:Weion/Sandbox/Games/HaloMCC/Halo3', [])
('User:Weion/Sandbox/Games/HaloMCC/HaloReach', [])
('West of Dead', [1016790, 1270990])
...
```

> On your issue of Control, the Microsoft store marks it as a console only offer so I think the list is probably the best for your use case right now.

Ahhh, good catch.  Slime Rancher was the other missing game and it is only for console and Android.

**Comment by MarsRaptor** [comment]
> That a-z game page shows 239 items, while I am getting 250 items from PCGamingWiki API

I would trust the store over the wiki, you would need to find the diff and find the issue there.

For the Halo games the wiki is somewhat scuffed as to linking to the Microsoft store page, some of them only go to the collection and some of them link to their own page also they are mostly DLC on steam and I don't know how that is handle by the api call.

Also... 
> 'User:Weion/Sandbox/Games/...'

...hmmmm.

@geeseven I will be transferring this to a discussion since it's kind of out of scope but the subject intrigues me.
